name: Go Test

on:
  workflow_dispatch:
   inputs:
      environment:
        description: 'Environment to run tests against'
        default: develop
        type: choice
        options:
          - develop
          - prod
  push:
   branches: [ main ]
  pull_request_target:
   branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
            ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: run testcase
      env:
        ENV: "${{ github.event.inputs.environment == 'prod' && 'prod' || 'develop' }}"
        SECRET: "${{ github.event.inputs.environment == 'prod' && secrets.PRODSECRET || secrets.DEVELOPSECRET }}"
        Web3SECRET: "${{ secrets.DEVELOPWEB3SECRET }}"
        MPCSECRET: "${{ secrets.DEVELOPMPCSECRET }}"
      run: |
        cd cobo_custody 
        go test -env $ENV -secret $SECRET -mpcSecret $MPCSECRET
